server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: application
    static_configs:
      - labels:
          job: application
          __path__: /var/log/app/*.log
    pipeline_stages:
      - json:
          expressions:
            datetime: datetime
            channel: channel
            level_name: level_name
      - json:
          expressions:
            endpoint: endpoint
            request_id: request_id
          source: context

      - labels:
          channel:
          level_name:
          request_id:
