version: "3.8"
services:
  webserver:
    image: traefik:v2.5
    restart: unless-stopped
    command:
      - --experimental.http3=true
      - --log.level=DEBUG
      - --api.insecure=true
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - ${WEB_PORT:-80}:80
    links:
      - php
      - grafana

  php:
    build:
      dockerfile: .docker/php/Dockerfile
      context: ./
    command:
      - vendor/bin/wait-for-it.sh
      - amqp:5672
      - --strict
      - --
      - vendor/bin/wait-for-it.sh
      - db:3306
      - --strict
    user: "${USER_ID:-1000}:${GROUP_ID:-1000}"
    restart: unless-stopped
    volumes:
      - ./.docker/php/php.ini:/usr/local/etc/php/conf.d/40-custom.ini:ro
      - ./.docker/data/composer:/home/appuser/.composer
      - ./project:/var/www
    environment:
      TZ: Europe/Moscow
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_LOGIN: ${DB_LOGIN}
      GITHUB_TOKEN: ${GITHUB_TOKEN}
      PHP_IDE_CONFIG: ${PHP_IDE_CONFIG:-}
      YII_DEBUG: 'true'
      YII_ENV: ${YII_ENV:-dev}
      XDEBUG_MODE: ${XDEBUG_MODE:-off}
      XDEBUG_CONFIG: "client_host=host.docker.internal"
      XDEBUG_TRIGGER: "yes"
      URL_PREFIX: /app
    env_file:
      - .env
    depends_on:
      - db
      - amqp
    extra_hosts:
      - host.docker.internal:${HOST_IP:-host.docker.internal}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.app.rule=Host(\"${DOMAIN}\") && Path(`/app`, `/app/{path:.*}`)"
      - "traefik.http.routers.app.entrypoints=web"

  db:
    image: mysql:5.7
    restart: unless-stopped
    volumes:
      - .docker/data/db:/var/lib/mysql
    ports:
      - ${DB_PORT:-3306}:3306
    environment:
      TZ: Europe/Moscow
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_LOGIN}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}

  amqp:
    image: rabbitmq:3-management
    restart: unless-stopped
    environment:
      RABBITMQ_DEFAULT_USER: ${AMQP_USER}
      RABBITMQ_DEFAULT_PASS: ${AMQP_PASSWORD}
    expose:
      - 5672
    ports:
      - ${AMQP_PORT:-15672}:15672

  loki:
    image: grafana/loki:2.4.1
    command: -config.file=/etc/loki/local-config.yaml

  promtail:
    image: grafana/promtail:2.4.1
    volumes:
      - ./project/runtime/logs:/var/log/app
      - ./project/runtime/logs-rr:/var/log/rr
      - .docker/data/promtail-data:/var/lib/promtail/positions
      - .docker/loki/promtail-local-config.yml:/etc/promtail/config.yml
    command: -config.file=/etc/promtail/config.yml
    links:
      - loki

  grafana:
    image: grafana/grafana-oss:latest
    user: 1000:1000
    volumes:
      - .docker/data/grafana:/var/lib/grafana
      - .docker/grafana/provisioning:/etc/grafana/provisioning
    environment:
      GF_SECURITY_ADMIN_USER: ${GRAFANA_USER:-yii-inform}
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_PASSWORD}
      GF_SERVER_ROOT_URL: http://${DOMAIN}/grafana
      GF_SERVER_SERVE_FROM_SUB_PATH: "true"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.grafana.rule=Host(\"${DOMAIN}\") && Path(`/grafana`, `/grafana/{path:.*}`)"
      - "traefik.http.routers.grafana.entrypoints=web"
