version: "3.8"
services:
  php:
    image: viktorprogger/yii-inform:latest
    command:
      - vendor/bin/wait-for-it.sh amqp:5672 --strict
      - --
      - vendor/bin/wait-for-it.sh db:3306 --strict
      - --
      - ./rr serve -c .rr.prod.yaml -o http.ssl.acme.domains[0]=${DOMAIN} -o http.pool.num_workers=${RR_WORKERS}
    user: "${USER_ID:-1000}:${GROUP_ID:-1000}"
    environment:
      TZ: Europe/Moscow
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_LOGIN: ${DB_LOGIN}
      GITHUB_TOKEN: ${GITHUB_TOKEN}
      YII_DEBUG: 'false'
      YII_ENV: 'prod'
      XDEBUG_MODE: 'off'
    env_file:
      - .env
    depends_on:
      - db
      - amqp
    ports:
      - ${SSL_PORT:-443}:443

  db:
    image: mysql:5.7
    restart: unless-stopped
    volumes:
      - .docker/data/db:/var/lib/mysql
    ports:
      - "127.0.0.1:${DB_PORT:-3306}:3306"
    environment:
      TZ: Europe/Moscow
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_LOGIN}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}


  amqp:
    image: rabbitmq:3-management
    restart: unless-stopped
    environment:
      RABBITMQ_DEFAULT_USER: ${AMQP_USER}
      RABBITMQ_DEFAULT_PASS: ${AMQP_PASSWORD}
    expose:
      - 5672
    ports:
      - "127.0.0.1:${AMQP_PORT:-15672}:15672"
