version: "3.8"
services:
#  webserver:
#    image: nginx:alpine
#    restart: unless-stopped
#    volumes:
#      - ./project:/var/www
#      - ./.docker/nginx/conf.d/:/etc/nginx/conf.d/
#    ports:
#      - ${WEB_PORT:-80}:80
#    links:
#      - php

  php:
    build: .docker/php
    restart: on-failure
    user: "${USER_ID:-1000}:${GROUP_ID:-1000}"
    volumes:
      - ./.docker/php/php.ini:/usr/local/etc/php/conf.d/40-custom.ini:ro
      - ./.docker/data/composer:/home/appuser/.composer
      - ./project:/var/www
    environment:
      TZ: Europe/Moscow
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_LOGIN: ${DB_LOGIN}
      PHP_IDE_CONFIG: ${PHP_IDE_CONFIG:-}
      XDEBUG_MODE: ${XDEBUG_MODE:-off}
      XDEBUG_CONFIG: "client_host=host.docker.internal"
      XDEBUG_TRIGGER: "yes"
    env_file:
      - .env
    links:
      - db
    extra_hosts:
      - host.docker.internal:${HOST_IP:-host.docker.internal}

  db:
    image: mysql:5.7
    restart: unless-stopped
    volumes:
      - .docker/data/db:/var/lib/mysql
    ports:
      - ${DB_PORT:-3306}:3306
    environment:
      TZ: Europe/Moscow
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_LOGIN}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}


  amqp:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: ${AMQP_USER}
      RABBITMQ_DEFAULT_PASS: ${AMQP_PASSWORD}
    expose:
      - 5672
    ports:
      - 15674:15672
