version: "3.8"
services:
#  webserver:
#    image: nginx:alpine
#    restart: unless-stopped
#    volumes:
#      - ./project:/var/www
#      - ./.docker/nginx/conf.d/:/etc/nginx/conf.d/
#    ports:
#      - ${WEB_PORT:-80}:80
#    links:
#      - php

  php:
    build:
      dockerfile: .docker/php/Dockerfile
      context: ./
    command:
      - vendor/bin/wait-for-it.sh
      - amqp:5672
      - --strict
      - --
      - vendor/bin/wait-for-it.sh
      - db:3306
      - --strict
      - --
      - ./rr
      - serve
      - -o
      - http.pool.num_workers=${RR_WORKERS}
    user: "${USER_ID:-1000}:${GROUP_ID:-1000}"
    restart: unless-stopped
    volumes:
      - ./.docker/php/php.ini:/usr/local/etc/php/conf.d/40-custom.ini:ro
      - ./.docker/data/composer:/home/appuser/.composer
      - ./project:/var/www
    environment:
      TZ: Europe/Moscow
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_LOGIN: ${DB_LOGIN}
      GITHUB_TOKEN: ${GITHUB_TOKEN}
      PHP_IDE_CONFIG: ${PHP_IDE_CONFIG:-}
      YII_DEBUG: 'true'
      YII_ENV: ${YII_ENV:-dev}
      XDEBUG_MODE: ${XDEBUG_MODE:-off}
      XDEBUG_CONFIG: "client_host=host.docker.internal"
      XDEBUG_TRIGGER: "yes"
    env_file:
      - .env
    depends_on:
      - db
      - amqp
    extra_hosts:
      - host.docker.internal:${HOST_IP:-host.docker.internal}
    ports:
      - "8888:80"
      - "8889:443"

  db:
    image: mysql:5.7
    restart: unless-stopped
    volumes:
      - .docker/data/db:/var/lib/mysql
    ports:
      - ${DB_PORT:-3306}:3306
    environment:
      TZ: Europe/Moscow
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_LOGIN}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}

  amqp:
    image: rabbitmq:3-management
    restart: unless-stopped
    environment:
      RABBITMQ_DEFAULT_USER: ${AMQP_USER}
      RABBITMQ_DEFAULT_PASS: ${AMQP_PASSWORD}
    expose:
      - 5672
    ports:
      - ${AMQP_PORT:-15672}:15672
