version: "3.8"
services:
  webserver:
    image: traefik:v2.5
    restart: unless-stopped
    command:
      - --experimental.http3=true
      #- --log.level=DEBUG
      - --api.insecure=true
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80
      - --entrypoints.ssl.address=:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - ${WEB_PORT:-80}:80
      - 443:443
    links:
      - php
      - grafana

  php:
    image: viktorprogger/yii-inform:latest
    volumes:
      - ./runtime/ssl:/var/www/runtime/ssl
      - logs:/var/www/runtime/logs
      - logs-rr:/var/www/runtime/logs-rr
    command:
      - vendor/bin/wait-for-it.sh
      - db:3306
      - --strict
      - --
      - vendor/bin/wait-for-it.sh
      - amqp:5672
      - --strict
      - --
      - ./rr
      - serve
      - -c
      - .rr.prod.yaml
      - -o
      - http.pool.num_workers=${RR_WORKERS}
      #- -o
      #- http.ssl.acme.domains=${DOMAIN}
    user: "${USER_ID:-1000}:${GROUP_ID:-1000}"
    environment:
      TZ: Europe/Moscow
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_LOGIN: ${DB_LOGIN}
      GITHUB_TOKEN: ${GITHUB_TOKEN}
      YII_DEBUG: 'false'
      YII_ENV: ${YII_ENV:-prod}
      XDEBUG_MODE: 'off'
    env_file:
      - .env
    depends_on:
      - db
      - amqp

  db:
    image: mysql:5.7
    restart: unless-stopped
    volumes:
      - .docker/data/db:/var/lib/mysql
    ports:
      - "127.0.0.1:${DB_PORT:-3306}:3306"
    environment:
      TZ: Europe/Moscow
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_LOGIN}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}

  amqp:
    image: rabbitmq:3-management
    restart: unless-stopped
    environment:
      RABBITMQ_DEFAULT_USER: ${AMQP_USER}
      RABBITMQ_DEFAULT_PASS: ${AMQP_PASSWORD}
    expose:
      - 5672

  loki:
    image: grafana/loki:2.4.1
    command: -config.file=/etc/loki/local-config.yaml

  promtail:
    image: grafana/promtail:2.4.1
    volumes:
      - logs:/var/log/app:ro
      - logs-rr:/var/log/rr:ro
      - .docker/data/promtail-data:/var/lib/promtail/positions
      - .docker/loki/promtail-local-config.yml:/etc/promtail/config.yml
    command: -config.file=/etc/promtail/config.yml
    links:
      - loki

  grafana:
    image: grafana/grafana-oss:latest
    user: 1000:1000
    volumes:
      - .docker/data/grafana:/var/lib/grafana
      - .docker/grafana/provisioning:/etc/grafana/provisioning
    environment:
      GF_SECURITY_ADMIN_USER: ${GRAFANA_USER:-yii-inform}
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_PASSWORD}
      GF_SERVER_ROOT_URL: http://${DOMAIN}/grafana
      GF_SERVER_SERVE_FROM_SUB_PATH: "true"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.grafana.rule=Host(\"${DOMAIN}\") && Path(`/grafana`, `/grafana/{path:.*}`)"
      - "traefik.http.routers.grafana.entrypoints=web"

volumes:
  logs:
  logs-rr:
