server:
  command: "php ./roadrunner-worker.php"

http:
  address: :80
  pool:
    num_workers: 4
  middleware: ["static", "headers"]
  static:
    dir:   "/public"
    forbid: [".php", ".htaccess"]
  headers:
    response:
      "Cache-Control": "no-cache"

reload:
  interval: 1s
  patterns: [ ".php" ]
  services:
    http:
      recursive: true
      dirs: [ "/" ]

logs:
  mode: production
  level: warn
