#!/usr/bin/env php
<?php

declare(strict_types=1);

use Viktorprogger\YiisoftInform\Infrastructure\ConsoleApplicationRunner;

require_once __DIR__ . '/preload.php';

// Run console application runner
$runner = new ConsoleApplicationRunner(true, null);
$runner->run();
