<?php

namespace Viktorprogger\YiisoftInform\SubDomain\GitHub\Infrastructure\Client;

use Github\Api\AbstractApi;
use Github\Client as GithubClient;

/**
 * @method Organization organization()
 * @method Organization organizations()
 */
final class Client extends GithubClient
{
    public function api($name): AbstractApi
    {
        if (in_array($name, ['organization', 'organizations'])) {
            return new Organization($this);
        }

        return parent::api($name); // TODO: Change the autogenerated stub
    }
}
